### ISSUE TITLE
Absence of LF files for Tennis and CivilComments

### ISSUE THREAD

**Issue by pranftw** [SprocketLab/fair-ws#1]
Hey Authors,

Thanks for open sourcing the code to your paper. However we found that the LFs for two datasets Tennis and CivilComments are missing in the Dropbox link. Do you have any plans to release them? Thanks!

**Comment by ch-shin** [comment]
Hi Pranav, thank you for reaching out! We uploaded LFs for two datasets Tennis and CivilComments in the dropbox link. Please let me know if there's anything else I can do to help!

**Comment by pranftw** [comment]
Hey Changho,
Thanks for the quick response. We are able to access the LFs for Tennis and CivilComments, thanks for that! Do you also have plans to release the files for CelebA?

**Comment by ch-shin** [comment]
Hi, I uploaded CelebA too. Please let us know if there are more missing datasets!

**Comment by pranftw** [comment]
Sure, thanks a lot!
